// <auto-generated />
using BillFlow.Database.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BillFlow.Database.Migrations;

[DbContext(typeof(BillFlowDbContext))]
[Migration("20260716140000_Phase2EmailLogoReminders")]
partial class Phase2EmailLogoReminders
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        // Snapshot updated with next `dotnet ef migrations add` when NuGet is available.
    }
}
