<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>BillFlow.BackgroundJobs</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.8" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DataAccess\BillFlow.Database\BillFlow.Database.csproj" />
    <ProjectReference Include="..\..\DataAccess\BillFlow.Repositories\BillFlow.Repositories.csproj" />
    <ProjectReference Include="..\..\DataAccess\BillFlow.Shared\BillFlow.Shared.csproj" />
  </ItemGroup>

</Project>
