<Project Sdk="Microsoft.NET.Sdk.Web">



  <PropertyGroup>

    <TargetFramework>net9.0</TargetFramework>

    <Nullable>enable</Nullable>

    <ImplicitUsings>enable</ImplicitUsings>

  </PropertyGroup>



  <ItemGroup>

    <PackageReference Include="ClosedXML" Version="0.105.0" />

    <PackageReference Include="DotNetEnv" Version="3.2.0" />

    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.8" />

    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>

    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.8" />

    <PackageReference Include="QuestPDF" Version="2026.6.0" />

    <PackageReference Include="StackExchange.Redis" Version="2.8.58" />

    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />

  </ItemGroup>



  <ItemGroup>

    <ProjectReference Include="..\..\DataAccess\BillFlow.Database\BillFlow.Database.csproj" />

    <ProjectReference Include="..\..\DataAccess\BillFlow.Repositories\BillFlow.Repositories.csproj" />

    <ProjectReference Include="..\..\DataAccess\BillFlow.Models\BillFlow.Models.csproj" />

    <ProjectReference Include="..\..\DataAccess\BillFlow.Shared\BillFlow.Shared.csproj" />

  </ItemGroup>



</Project>


